# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            A Little Empty Attic
tagline:          'Arbitrary Musings from Daniel Mintz'
description:      'A blog to collect the internet musings of Daniel Mintz'
url:              http://danielmintz.com
baseurl:          /

author:
  name:           'Daniel Mintz'
  url:            https://twitter.com/dwmintz

paginate:         5

# Custom vars
version:          2.1.0

# Includes an icon in the footer for each user name you enter
footer-links:
  github: dwmintz
  twitter: danielmintz
  facebook: danielwmintz
  linkedin: danielmintz